spring:
  # 配置文件上传大小限制
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# minio
fs:
  minio:
    endpoint: http://119.91.113.111:9000
    fileHost: http://119.91.113.111:9000
    accessKey: imadmin
    secretKey: imadmin123
    bucketName: im-admin
