im:
  server:
    host: 0.0.0.0
    port: 8001
    nodeId: im-01
    bucketNum: 32

grpc:
  server:
    port: 6001
  client:

spring:
  application:
    name: im-comet-grpc-server


task:
  pool:
    # 核心线程数
    corePoolSize: 20
    # 最大线程数
    maxPoolSize: 200
    # 活跃时间
    keepAliveSeconds: 300
    # 队列容量
    queueCapacity: 50

etcd:
  endpoints:
    - 119.91.113.111:2379
  prefix: /im/comet/
